### ISSUE TITLE
Installation of O.R.C.A on AWS

### ISSUE THREAD

**Issue by deepakarchinnova** [Archinnova/vendors#1]
[Orca Installation Prerequisite Documentation.pdf](https://github.com/Archinnova/vendors/files/840923/Orca.Installation.Prerequisite.Documentation.pdf)

@zeinazrien have a look at this

**Comment by zeinazrien** [comment]
@deepakarchinnova I got this error while installing mysql-client
![1](https://cloud.githubusercontent.com/assets/25415358/23896658/976f509e-08c3-11e7-99f0-aa9d99ad4483.PNG)

**Comment by deepakarchinnova** [comment]
@zeinazrien was there any progress?

**Comment by zeinazrien** [comment]
@deepakarchinnova I finished the installation successfully yesterday
